### ISSUE TITLE
psutil returning 'NoneType'

### ISSUE THREAD

**Issue by OliverMatthews** [OliverMatthews/rubiksCube#32]
`Traceback (most recent call last):
  File "main.py", line 331, in <module>
    menuBool = mainMenu()
  File "main.py", line 44, in mainMenu
    menuBool = option2()
  File "main.py", line 121, in option2
    dev.runManySimulations(numberOfSimulations)
  File "/home/pi/Documents/rubiksCube/rubiksCube/dev.py", line 107, in runManySimulations
    cores = int(psutil.cpu_count(logical=False))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

Running on Raspberry Pi 4B+, Raspbian GNU/Linux 10 (buster).

**Comment by OliverMatthews** [comment]
Fixed in #37
